---
# tasks file for bvansomeren.jail-jumphost

- name: ensure pam_google_authenticator installed
  package:
    name: "{{ jumphost_packages }}"
    state: present
  when: jumphost_two_factor

- set_fact:
    ssh_authentication_methods: "publickey,keyboard-interactive"
  when: jumphost_two_factor

- name: ensure sshd is configured
  import_role:
    name: bvansomeren.sshd
  vars:
    ssh_use_pam: "yes"
    ssh_challenge_response_auth: "yes"
    sshd_custom_options:
    - name: AllowTcpForwarding
      value: "yes"
    - name: PasswordAuthentication
      value: "no"
    - name: AuthenticationMethods 
      value: "{{ ssh_authentication_methods }}"

- name: ensure log folder for auditing
  file:
    path: "{{ jumphost_log_folder }}"
    state: directory
    mode: 0770

- name: ensure /etc/ssh/ssh_config has hosts
  blockinfile:
    dest: /etc/ssh/ssh_config
    marker: "# {mark} Host added by Ansible: {{ item.hostname }}"
    content: |
      Host {{ item.hostname }}
        Hostname {{ item.ip }}
  with_items: "{{ jumphost_servers }}"


#- name: ensure logging shell is installed
#  template:
#    src: shell
#    dest: /usr/local/bin/bastion-shell
#    mode: "a+x"
